; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "App0stol"
#define MyAppVersion "1.0"
#define MyAppPublisher "Permaquim S.A."
#define MyAppURL "https://permaquim.com/"
#define MyAppExeName "APP.0.STOL.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{92A22FE3-0021-474A-853C-7FFB2CFB4229}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=C:\Permaquim\{#MyAppName}
DisableDirPage=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=App0stol.Setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
SetupIconFile="\\filesrv\DESARROLLO\Proyectos\Depositario\Publicaciones\PQ.ico"
WizardSmallImageFile="\\filesrv\DESARROLLO\Proyectos\Depositario\Publicaciones\PQ.bmp"
WizardImageFile="\\filesrv\DESARROLLO\Proyectos\Depositario\Publicaciones\\Permaquim.Logo.bmp"
AppCopyright=Permaquim S.A.
ShowLanguageDialog=no
UninstallDisplayName=App0stol
UninstallDisplayIcon={app}\APP.0.STOL.exe
AllowRootDirectory=True
OutputDir=C:\instaladores\App0stol

[Languages]
;Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"


[Files]
Source: "..\App0stol\APP.0.STOL.exe"; DestDir: "{app}"; Flags: ignoreversion; Components: App0stol
Source: "..\App0stol\D3DCompiler_47_cor3.dll"; DestDir: "{app}"; Flags: ignoreversion; Components: App0stol
Source: "..\App0stol\PenImc_cor3.dll"; DestDir: "{app}"; Flags: ignoreversion; Components: App0stol
Source: "..\App0stol\Permaquim.Depositary.ApplicationStatusMonitor.exe"; DestDir: "{app}"; Flags: ignoreversion; Components: SincronizacionApp0stol
Source: "..\App0stol\ServiceTasks.json"; DestDir: "{app}"; Flags: ignoreversion; Components: SincronizacionApp0stol
Source: "..\App0stol\Tasks.json"; DestDir: "{app}"; Flags: ignoreversion; Components: SincronizacionApp0stol
Source: "..\App0stol\Permaquim.Depositary.Launcher.exe"; DestDir: "{app}"; Flags: ignoreversion; Components: App0stol
Source: "..\App0stol\Permaquim.Depositary.Sincronization.Console.exe"; DestDir: "{app}"; Flags: ignoreversion; Components: SincronizacionApp0stol App0stol
Source: "..\App0stol\PresentationNative_cor3.dll"; DestDir: "{app}"; Flags: ignoreversion; Components: App0stol
Source: "..\App0stol\sni.dll"; DestDir: "{app}"; Flags: ignoreversion; Components: App0stol
Source: "..\App0stol\Tasks.json"; DestDir: "{app}"; Flags: ignoreversion; Components: App0stol
Source: "..\App0stol\vcruntime140_cor3.dll"; DestDir: "{app}"; Flags: ignoreversion; Components: App0stol
Source: "..\App0stol\wpfgfx_cor3.dll"; DestDir: "{app}"; Flags: ignoreversion; Components: App0stol
Source: "..\App0stol\PQ.ico"; DestDir: "{app}"; Flags: ignoreversion; Components: App0stol
Source: "..\App0stol\Resources\Images\Login.png"; DestDir: "{app}\Resources\Images"; Flags: ignoreversion; Components: App0stol
Source: "..\App0stol\Resources\Images\logo.png"; DestDir: "{app}\Resources\Images"; Flags: ignoreversion; Components: App0stol
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\AUTORUN.INF"; DestDir: "{app}\SQLEXPRADV_x64_ENU"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\ConfigurationFile.ini"; DestDir: "{app}\SQLEXPRADV_x64_ENU"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\MEDIAINFO.XML"; DestDir: "{app}\SQLEXPRADV_x64_ENU"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\PackageId.dat"; DestDir: "{app}\SQLEXPRADV_x64_ENU"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\SETUP.EXE"; DestDir: "{app}\SQLEXPRADV_x64_ENU"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\SETUP.EXE.CONFIG"; DestDir: "{app}\SQLEXPRADV_x64_ENU"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\SQLSETUPBOOTSTRAPPER.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\1033_ENU_LP\MEDIAINFO.XML"; DestDir: "{app}\SQLEXPRADV_x64_ENU\1033_ENU_LP"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\README.HTM"; DestDir: "{app}\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\1033\LICENSE_DEV.RTF"; DestDir: "{app}\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\1033"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\1033\LICENSE_EVAL.RTF"; DestDir: "{app}\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\1033"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\1033\LICENSE_EXPR.RTF"; DestDir: "{app}\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\1033"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\1033\PYTHONLICENSE.RTF"; DestDir: "{app}\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\1033"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\1033\README.HTM"; DestDir: "{app}\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\1033"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\1033\ROPENLICENSE.RTF"; DestDir: "{app}\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\1033"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup\CONN_INFO_LOC.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup\SMO_EXTENSIONS_LOC.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup\SMO_LOC.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup\SQLBROWSER.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup\SQLSUPPORT.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup\SQL_COMMON_CORE_LOC.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup\SQL_DMF_LOC.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup\SQL_ENGINE_CORE_INST_LOC.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup\SQL_ENGINE_CORE_SHARED_LOC.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup\SQL_TOOLS_EXTENSIONS_LOC.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup\SQL_TOOLS_LOC.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup\SQL_XEVENT_LOC.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup\x64\MSODBCSQL.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup\x64\MSOLEDBSQL.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup\x64\SQLLOCALDB.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup\x64\SQLNCLI.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup\x64\SQLWRITER.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup\x64\TSQLLANGUAGESERVICE.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\Setup\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\20220926_201109\ConfigurationFile.ini"; DestDir: "{app}\SQLEXPRADV_x64_ENU\20220926_201109"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\20220926_201109\Detail.txt"; DestDir: "{app}\SQLEXPRADV_x64_ENU\20220926_201109"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\20220926_201109\Detail_Local.txt"; DestDir: "{app}\SQLEXPRADV_x64_ENU\20220926_201109"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\20220926_201109\SqlSupport_Cpu64_1.log"; DestDir: "{app}\SQLEXPRADV_x64_ENU\20220926_201109"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\20220926_201109\SystemConfigurationCheck_Report.htm"; DestDir: "{app}\SQLEXPRADV_x64_ENU\20220926_201109"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\20220926_201109\resources\ProgressError.ico"; DestDir: "{app}\SQLEXPRADV_x64_ENU\20220926_201109\resources"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\20220926_201109\resources\ProgressSkip.ico"; DestDir: "{app}\SQLEXPRADV_x64_ENU\20220926_201109\resources"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\20220926_201109\resources\ProgressSuccess.ico"; DestDir: "{app}\SQLEXPRADV_x64_ENU\20220926_201109\resources"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\20220926_201109\resources\ProgressWarn.ico"; DestDir: "{app}\SQLEXPRADV_x64_ENU\20220926_201109\resources"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\redist\VisualStudioShell\VCRuntimes\VC_REDIST_X64.EXE"; DestDir: "{app}\SQLEXPRADV_x64_ENU\redist\VisualStudioShell\VCRuntimes"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\redist\VisualStudioShell\VCRuntimes\VC_REDIST_X86.EXE"; DestDir: "{app}\SQLEXPRADV_x64_ENU\redist\VisualStudioShell\VCRuntimes"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\resources\1033\SETUP.RLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\resources\1033"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\ADDNODE.XML"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\COMPLETECLUSTERWIZARD.XML"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\COMPLETEIMAGEWIZARD.XML"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\COMPONENTUPDATE.XML"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\CONFIGURATION.UICFG"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\EDITIONUPGRADEWIZARD.XML"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\FIXSQLREGISTRYKEY_X64.EXE"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\FIXSQLREGISTRYKEY_X64.EXE.CONFIG"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\FIXSQLREGISTRYKEY_X86.EXE"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\FIXSQLREGISTRYKEY_X86.EXE.CONFIG"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\INSTALLCLUSTERWIZARD.XML"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\INSTALLWIZARD.XML"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\INSTAPI150.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\LANDINGPAGE.EXE"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\LANDINGPAGE.EXE.CONFIG"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.ANALYSISSERVICES.ADOMDCLIENT.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.ANALYSISSERVICES.CORE.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.ANALYSISSERVICES.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.ANALYSISSERVICES.SPCLIENT.INTERFACES.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.ANALYSISSERVICES.TABULAR.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.ANALYSISSERVICES.TABULAR.JSON.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.DIAGNOSTICS.TRACING.EVENTSOURCE.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.NETENTERPRISESERVERS.EXCEPTIONMESSAGEBOX.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQL.CHAINER.PACKAGE.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQL.CHAINER.PACKAGE.XMLSERIALIZERS.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQL.CHAINER.PACKAGEDATA.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQL.CHAINER.PRODUCT.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQL.CHAINER.PRODUCT.XMLSERIALIZERS.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CHAINER.EXTENSIONCOMMON.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CHAINER.EXTENSIONCOMMON.XMLSERIALIZERS.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CHAINER.INFRASTRUCTURE.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CHAINER.INFRASTRUCTURE.XMLSERIALIZERS.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CHAINER.WORKFLOWDATA.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CHAINER.WORKFLOWDATA.XMLSERIALIZERS.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.AGENTEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.ASEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.ASTELEMETRYEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.BOOTSTRAPEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.BOOTSTRAPEXTENSION.XMLSERIALIZERS.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.CLUSTER.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.CLUSTER.XMLSERIALIZERS.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.CONFIGEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.CONFIGEXTENSION.XMLSERIALIZERS.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.DISTRIBUTEDREPLAYEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.EXTENSIBILITY_CONFIGEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.FULLTEXT_CONFIGEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.IMPY_CONFIGEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.IMR_CONFIGEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.INSTALLWIZARD.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.INSTALLWIZARDFRAMEWORK.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.INSTALLWIZARDFRAMEWORK.XMLSERIALIZERS.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.ISMASTEREXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.ISTELEMETRYCONFIGEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.ISWORKEREXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.MANAGEMENTTOOLSEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.MSIEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.MSIEXTENSION.XMLSERIALIZERS.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.POLYBASECONFIGEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.POLYBASEJAVACONFIGEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.POWERSHELLEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.REPL_CONFIGEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.RSEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.RULESENGINEEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.RULESENGINEEXTENSION.XMLSERIALIZERS.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.SAA_CONFIGEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.SCO.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.SCO.XMLSERIALIZERS.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.SCOEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.SETUPEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.SETUPEXTENSION.XMLSERIALIZERS.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.SLPEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.SMARTSETUPEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.SMARTSETUPEXTENSION.XMLSERIALIZERS.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.SMPY_CONFIGEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.SMR_CONFIGEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.SNISERVERCONFIGEXT.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.SQLBROWSEREXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.SQLCONFIGBASE.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.SQLCONFIGBASE.XMLSERIALIZERS.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.SQLSERVER_CONFIGEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.SSISEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.TELEMETRYCONFIGEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.UIEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.UIEXTENSION.XMLSERIALIZERS.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.UTILITYEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.WIZARDFRAMEWORK.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.WIZARDFRAMEWORK.XMLSERIALIZERS.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.WMIINTEROP.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.XMLSERIALIZERS.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONFIGURATION.XTP.CONFIGEXTENSION.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CONNECTIONINFO.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.CUSTOMCONTROLS.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.DATAWAREHOUSE.WORKLOADDEPLOYMENT.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.DEPLOYMENT.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.DEPLOYMENT.XMLSERIALIZERS.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.DIAGNOSTICS.STRACE.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.DISCOVERY.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.DISCOVERY.XMLSERIALIZERS.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.DMF.COMMON.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.DMF.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.INSTAPI.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.INTEROP.FIREWALLAPI.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.INTEROP.TASKSCHD.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.INTEROP.WUAPILIB.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.MANAGEMENT.CONTROLS.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.MANAGEMENT.SDK.SFC.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.SETUP.CHAINER.WORKFLOW.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.SETUP.CHAINER.WORKFLOW.XMLSERIALIZERS.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.SMO.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.SQLCLRPROVIDER.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.SQLENUM.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.SSTRING.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MICROSOFT.SQLSERVER.USAGETRACKING.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MSVCP140.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\MSVCP140_1.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\NEWTONSOFT.JSON.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\PACKAGE.XSD"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\PIDGENX.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\PIDPRIVATECONFIGOBJECTMAPS.XML"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\PREPARECLUSTERWIZARD.XML"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\PREPAREIMAGEWIZARD.XML"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\REMOVENODE.XML"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\REPAIRWIZARD.XML"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\RSETUP.EXE"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\RUNRULESUI.XML"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\SCENARIOENGINE.EXE"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\SCENARIOENGINE.EXE.CONFIG"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\SHELLOBJECTS.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\SQLBOOT.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\SQLCAB.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\SQLCONF.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\SQLMU.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\SQLPROCESSSUB.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\SQLSCCN.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\UNINSTALLWIZARD.XML"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\UPGRADEWIZARD.XML"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\VCCORLIB140.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\VCRUNTIME140.DLL"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\Setup\CONN_INFO.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\Setup\MSMPISETUP.EXE"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\Setup\RSFX.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\Setup\SMO.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\Setup\SMO_EXTENSIONS.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\Setup\SQL_AZUL_JAVA.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\Setup\SQL_BATCHPARSER.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\Setup\SQL_COMMON_CORE.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\Setup\SQL_DIAG.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\Setup\SQL_DMF.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\Setup\SQL_ENGINE_CORE_INST.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\Setup\SQL_ENGINE_CORE_SHARED.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\Setup\SQL_EXTENSIBILITY.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\Setup\SQL_FULLTEXT.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\Setup\SQL_INST_JAVA.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\Setup\SQL_INST_MPY.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\Setup\SQL_INST_MR.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\Setup\SQL_POLYBASE_CORE_INST.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\Setup\SQL_POLYBASE_JAVA_INST.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\Setup\SQL_SHARED_AA.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\Setup\SQL_SHARED_MPY.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\Setup\SQL_SHARED_MR.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\Setup\SQL_TOOLS.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\Setup\SQL_TOOLS_EXTENSIONS.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\SQLEXPRADV_x64_ENU\x64\Setup\SQL_XEVENT.MSI"; DestDir: "{app}\SQLEXPRADV_x64_ENU\x64\Setup"; Flags: ignoreversion deleteafterinstall; Components: SQLServerExpress2019
Source: "..\..\..\..\Instaladores\NPIPrinter_DS3.1.0.0_20140521 ENG\NPIP_DSTooll2.1.0.0_20130521\NII Printer_DS_Tool.cab"; DestDir: "{app}\NPIP_DSTooll2.1.0.0_20130521"; Flags: ignoreversion deleteafterinstall; Components: NII_Printer
Source: "..\..\..\..\Instaladores\NPIPrinter_DS3.1.0.0_20140521 ENG\NPIP_DSTooll2.1.0.0_20130521\Setup.exe"; DestDir: "{app}\NPIP_DSTooll2.1.0.0_20130521"; Flags: ignoreversion deleteafterinstall; Components: NII_Printer
Source: "..\..\..\..\Instaladores\NPIPrinter_DS3.1.0.0_20140521 ENG\NPIP_DSTooll2.1.0.0_20130521\Setup.xml"; DestDir: "{app}\NPIP_DSTooll2.1.0.0_20130521"; Flags: ignoreversion deleteafterinstall; Components: NII_Printer
Source: "..\..\..\..\Instaladores\NPIPrinter_DS3.1.0.0_20140521 ENG\NPIP_DSTooll2.1.0.0_20130521\work\NExFcSv.exe"; DestDir: "{app}\NPIP_DSTooll2.1.0.0_20130521\work"; Flags: ignoreversion deleteafterinstall; Components: NII_Printer
Source: "..\..\..\..\Instaladores\NPIPrinter_DS3.1.0.0_20140521 ENG\NPIP_DSTooll2.1.0.0_20130521\work\NExL_RSV.exe"; DestDir: "{app}\NPIP_DSTooll2.1.0.0_20130521\work"; Flags: ignoreversion deleteafterinstall; Components: NII_Printer
Source: "..\..\..\..\Instaladores\NPIPrinter_DS3.1.0.0_20140521 ENG\NPIP_DSTooll2.1.0.0_20130521\work\NExRmCL.exe"; DestDir: "{app}\NPIP_DSTooll2.1.0.0_20130521\work"; Flags: ignoreversion deleteafterinstall; Components: NII_Printer
Source: "..\..\..\..\Instaladores\NPIPrinter_DS3.1.0.0_20140521 ENG\NPIP_DSTooll2.1.0.0_20130521\work\NExShSV.exe"; DestDir: "{app}\NPIP_DSTooll2.1.0.0_20130521\work"; Flags: ignoreversion deleteafterinstall; Components: NII_Printer
Source: "..\..\..\..\Instaladores\NPIPrinter_DS3.1.0.0_20140521 ENG\NPIP_DSTooll2.1.0.0_20130521\work\NExStPrt.exe"; DestDir: "{app}\NPIP_DSTooll2.1.0.0_20130521\work"; Flags: ignoreversion deleteafterinstall; Components: NII_Printer
Source: "..\..\..\..\Instaladores\NPIPrinter_DS3.1.0.0_20140521 ENG\NPIP_DSTooll2.1.0.0_20130521\work\NII Printer_DS USB.PPI"; DestDir: "{app}\NPIP_DSTooll2.1.0.0_20130521\work"; Flags: ignoreversion deleteafterinstall; Components: NII_Printer
Source: "..\..\..\..\Instaladores\NPIPrinter_DS3.1.0.0_20140521 ENG\NPIP_DSTooll2.1.0.0_20130521\work\NII Printer_DS.PPI"; DestDir: "{app}\NPIP_DSTooll2.1.0.0_20130521\work"; Flags: ignoreversion deleteafterinstall; Components: NII_Printer
Source: "..\..\..\..\Instaladores\NPIPrinter_DS3.1.0.0_20140521 ENG\InstallFile\NIIPrinter_DS.INF"; DestDir: "{app}\NPIP_DSTooll2.1.0.0_20130521\work"; Flags: ignoreversion deleteafterinstall; Components: NII_Printer
Source: "..\DB\Depositario.mdf"; DestDir: "{app}\DB"; Flags: ignoreversion
Source: "..\DB\Depositario_log.ldf"; DestDir: "{app}\DB"; Flags: ignoreversion
Source: "..\DepositaryWebAdministrator\*"; DestDir: "{app}\DepositaryWebAdministrator"; Flags: ignoreversion createallsubdirs recursesubdirs; Components: App0stolAdministracionWeb
Source: "..\WebApi\*"; DestDir: "{app}\DepositaryWebapi"; Flags: ignoreversion createallsubdirs recursesubdirs; Components: App0stolWebapi
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: "..\App0stol\appsettings.json"; DestDir: "{app}"; Components: App0stol SincronizacionApp0stol

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\PQ.ico"; IconFilename: "{app}\PQ.ico"

[Run]
Filename: "SC"; Parameters: "CREATE ""Permaquim.Appstatus.Monitor"" binpath= {app}\Permaquim.Depositary.ApplicationStatusMonitor.exe start= auto"; Flags: shellexec; Components: SincronizacionApp0stol
Filename: "NET"; Parameters: "START ""Permaquim.Appstatus.Monitor"""; Flags: shellexec
Filename: "{app}\SQLEXPRADV_x64_ENU\SETUP.EXE"; Parameters: "/ConfigurationFile=ConfigurationFile.ini"; Components: SQLServerExpress2019
Filename: "pnputil"; Parameters: "-i -a ""{app}\NPIPrinter_DS3.1.0.0_20140521 ENG\InstallFile\NIIPrinter_DS.INF"""; Components: NII_Printer

[Components]
Name: "SQLServerExpress2019"; Description: "SQLServerExpress2019 database engine"; Types: custom full
Name: "App0stol"; Description: "Depositario"; Types: custom full
Name: "SincronizacionApp0stol"; Description: "Sincronización App0stol"; Types: custom full
Name: "App0stolWebapi"; Description: "App0stol Webapi"; Types: custom full
Name: "App0stolAdministracionWeb"; Description: "App0stol Administración Web"; Types: custom full
Name: "NII_Printer"; Description: "NII Printer"; Types: custom full

[UninstallRun]
Filename: "NET"; Parameters: "STOP ""Permaquim.Appstatus.Monitor"" binpath= {app}\Permaquim.Depositary.ApplicationStatusMonitor.exe"; Flags: shellexec
Filename: "SC"; Parameters: "DELETE ""Permaquim.Appstatus.Monitor"" binpath= {app}\Permaquim.Depositary.ApplicationStatusMonitor.exe"; Flags: shellexec
